[server]
port = 5000
address = "0.0.0.0"
headless = true
maxUploadSize = 200

[theme]
primaryColor = "#4F8EF7"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"

[browser]
gatherUsageStats = false