# Netlify Configuration for Podcast Script Generator

[build]
  base = "."
  publish = "dist/public"
  command = "npm ci && npm run build && cp netlify/_redirects dist/public/_redirects"

[build.environment]
  NODE_VERSION = "22"
  NPM_VERSION = "10"
  NPM_FLAGS = "--legacy-peer-deps"
  NODE_ENV = "production"

# Redirect all requests to index.html for React Router
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# API routes for Netlify Functions (if using serverless)
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Environment variables (configure in Netlify dashboard)
[context.production.environment]
  NODE_ENV = "production"

[context.deploy-preview.environment]
  NODE_ENV = "development"

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"